service: serverless-graphql-boilerplate

provider:
  name: aws
  runtime: nodejs8.10

  # you can overwrite defaults here
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-2'}

  environment:
    NODE_ENV: ${opt:NODE_ENV, 'dev'}

functions:
  graphql:
    handler: index.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: index.graphql
    events:
      - http:
          path: playground
          method: get

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000
